[package]
name = "price-oracle-service"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql.workspace = true
linera-sdk.workspace = true
price-oracle = { path = "../../price-oracle" }

[[bin]]
name = "price_oracle_service"
path = "src/main.rs"






