[package]
name = "price-oracle-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
linera-sdk.workspace = true
price-oracle = { path = "../../price-oracle" }

[[bin]]
name = "price_oracle_contract"
path = "src/main.rs"






