[package]
name = "price-oracle"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql.workspace = true
linera-sdk.workspace = true
linera-views.workspace = true
serde.workspace = true
thiserror.workspace = true
